//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTestLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BTestDbContext : DbContext
    {
        public BTestDbContext()
            : base("name=BTestDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllCorrelation> AllCorrelations { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Food_Index> Food_Index { get; set; }
        public virtual DbSet<General_recommendation> General_recommendations { get; set; }
        public virtual DbSet<Health_Questionnaire> Health_Questionnaires { get; set; }
        public virtual DbSet<Index> Indices { get; set; }
        public virtual DbSet<Index_Number_Recommendation_Id> Index_Number_Recommendation_Id { get; set; }
        public virtual DbSet<Recommendation> Recommendations { get; set; }
        public virtual DbSet<Registered_User> Registered_Users { get; set; }
        public virtual DbSet<Report_Index> Report_Index { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User_Report> User_Reports { get; set; }
    }
}
