//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTestLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Index
    {
        public int Food_Id { get; set; }
        public int Index_Id { get; set; }
        public string Index_Type { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Index Index { get; set; }
    }
}
