//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTestLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Index
    {
        public int Report_Id { get; set; }
        public int Index_Number { get; set; }
        public double Value { get; set; }
    
        public virtual Index Index { get; set; }
        public virtual User_Report User_Report { get; set; }
    }
}
